### PR TITLE
File Transfer limits: owner and group fix.

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline

**Comment by merlin-northern** [comment]
@mender-test-bot  start pipeline please :)

**Review by alfrunes — APPROVED** [review]

**Comment by lluiscampos** [comment]
Smells to me like it should have a `Changelog` tag (and therefor a future cherry-pick to release branch).

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please :*

**Review by tranchitella — APPROVED** [review]

**Comment by lluiscampos** [comment]
> ... and therefore a future cherry-pick to release branch.

@merlin-northern Please don't forget the cherry-pick

**Comment by lluiscampos** [comment]
By the way, the bot should have send the reminder (not me!). I'll look into it (the bot code, not the cherry-pick)

**Comment by lluiscampos** [comment]
> By the way, the bot should have send the reminder (not me!). I'll look into it (the bot code, not the cherry-pick)

See https://github.com/mendersoftware/integration-test-runner/pull/86

**Pull request merged**
