### PR TITLE
WIP DESTDIR set to default empty so we do not use // in paths

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please

**Comment by merlin-northern** [comment]
please ignore for now -- work in progress.

**Comment by oleorhagen** [comment]
@merlin-northern close or keep?

**Comment by merlin-northern** [comment]
> @merlin-northern close or keep?

can it be a draft? I wonder when I will have time to finish all those extra-out-of-bands followups.

**Comment by oleorhagen** [comment]
> > @merlin-northern close or keep?
> 
> can it be a draft? I wonder when I will have time to finish all those extra-out-of-bands followups.

Please just close it :pray: 

Just keep a note in your TODO list locally :smile_cat:

**Comment by merlin-northern** [comment]
> > > @merlin-northern close or keep?
> > 
> > 
> > can it be a draft? I wonder when I will have time to finish all those extra-out-of-bands followups.
> 
> Please just close it 🙏
> 
> Just keep a note in your TODO list locally 😸

okey

**Pull request closed without merging**
