### PR TITLE
1.0.x: MEN-5290: Several robustness fixes around re-connection

### PR DESCRIPTION
**Pull request by lluiscampos**
Cherry-pick of #51.

### CODE REVIEW

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline :long_drum:

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline --pr meta-mender/1552

**Comment by lluiscampos** [comment]
Build for Mender 2.6.x @ [Pipeline 440088069](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/440088069)

**Comment by lluiscampos** [comment]
@mzedel Can you look at the second commit?

**Review by mzedel — APPROVED** [review]
Based on the changes to the mod files this looks fine, but the check does a way better job than me looking at the hashes...
~One other thing though:~
~_Copyright 2022 Northern.tech' not found in LICENSE. Wrong year maybe?_~
~I guess we run into these more frequently this time of a year 😉~

**Comment by lluiscampos** [comment]
@mzedel Funny enough, the cherry pick is "from last year" so it passed the check... but the `go mod tidy` fix is "from this year" :partying_face:

**Pull request merged**
