### PR TITLE
Add behavior to src_path parameter to upload session endpoint

### PR DESCRIPTION
**Pull request by alfrunes**
This PR is based on top of #24

### CODE REVIEW

**Review by tranchitella — APPROVED** [review]
Looks good (I only checked the code, not the unit tests)

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Comment by alfrunes** [comment]
Please note that in order for these changes to have any visible effect to the end user, we need to update deviceconnect and mender-cli to use the new `src_path` parameter.

**Comment by tranchitella** [comment]
Best with https://github.com/mendersoftware/deviceconnect/pull/81

**Pull request merged**
